### ISSUE TITLE
duplicate entries synced

### ISSUE THREAD

**Issue by towry** [getmatterapp/logseq-matter#3]
I installed this plugin at my home laptop, synced once.

After I got it setup at my work pc, I synced again, the entries was synced again result in duplicated.

**Comment by hunterclarke** [comment]
@towry sync is a tricky thing to get right. What are you using to sync Logseq instances? And could you share a screenshot of an example of duplicate entries?

This sounds like there is a race condition happening where both syncs are happening at the same time, so the independent Logseq graphs are stepping on each other's toes.

**Comment by towry** [comment]
> sync is a tricky thing to get right. What are you using to sync Logseq instances?

I totally understand this. 

> What are you using to sync Logseq instances

I have one logseq db(like obsidian vault?), I just setup the sync mechanism, those folders and files are synced.

1. config/
2. preferences.json
3. settings/logseq-matter.json (contains token etc, credential stuff)

I think this will just work, and just tested, seems working fine on matter sync. same `settings/logseq-matter.json` is used, so no issue anymore I think.

I am closing this issue, if you have more suggestion, that would be appreciated. ❤️

This is the duplicated entries looks like:

![截屏2022-12-13 08 56 54](https://user-images.githubusercontent.com/8279858/207200019-f4c2922f-4ecd-4ac6-b74e-ca389c8c2ae1.png)

**Comment by hunterclarke** [comment]
@towry are you using the built in Logseq sync function? Or iCloud/Dropbox? Or some other form of sync?

**Comment by towry** [comment]
@hunterclarke The global config (~/.logseq)is synced with git.

The single logseq db is located at my iCloud, so it is synced with iCloud.
